import type { DeviceCategory } from "@/lib/trade/shared";

export type SeedDeviceModel = {
  id: string;
  category: DeviceCategory;
  brand: string;
  model: string;
  systemMaxBrandNew: number;
  systemMaxExcellent: number;
  systemMaxGood: number;
  systemMaxFair: number;
  systemMaxCrackedWorking: number;
  systemMaxCrackedNotWorking: number;
};

export const seedDeviceModels: SeedDeviceModel[] = [
  {
    id: "apple-iphone-15",
    category: "phone",
    brand: "Apple",
    model: "iPhone 15",
    systemMaxBrandNew: 520,
    systemMaxExcellent: 470,
    systemMaxGood: 430,
    systemMaxFair: 380,
    systemMaxCrackedWorking: 260,
    systemMaxCrackedNotWorking: 150,
  },
  {
    id: "apple-iphone-14",
    category: "phone",
    brand: "Apple",
    model: "iPhone 14",
    systemMaxBrandNew: 430,
    systemMaxExcellent: 390,
    systemMaxGood: 355,
    systemMaxFair: 315,
    systemMaxCrackedWorking: 220,
    systemMaxCrackedNotWorking: 130,
  },
  {
    id: "apple-iphone-13",
    category: "phone",
    brand: "Apple",
    model: "iPhone 13",
    systemMaxBrandNew: 355,
    systemMaxExcellent: 315,
    systemMaxGood: 280,
    systemMaxFair: 240,
    systemMaxCrackedWorking: 165,
    systemMaxCrackedNotWorking: 100,
  },
  {
    id: "samsung-galaxy-s24",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy S24",
    systemMaxBrandNew: 470,
    systemMaxExcellent: 420,
    systemMaxGood: 385,
    systemMaxFair: 330,
    systemMaxCrackedWorking: 225,
    systemMaxCrackedNotWorking: 135,
  },
  {
    id: "samsung-galaxy-s23",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy S23",
    systemMaxBrandNew: 360,
    systemMaxExcellent: 320,
    systemMaxGood: 290,
    systemMaxFair: 250,
    systemMaxCrackedWorking: 175,
    systemMaxCrackedNotWorking: 105,
  },
  {
    id: "google-pixel-8",
    category: "phone",
    brand: "Google",
    model: "Pixel 8",
    systemMaxBrandNew: 340,
    systemMaxExcellent: 300,
    systemMaxGood: 270,
    systemMaxFair: 230,
    systemMaxCrackedWorking: 155,
    systemMaxCrackedNotWorking: 95,
  },
  {
    id: "google-pixel-7",
    category: "phone",
    brand: "Google",
    model: "Pixel 7",
    systemMaxBrandNew: 250,
    systemMaxExcellent: 220,
    systemMaxGood: 195,
    systemMaxFair: 165,
    systemMaxCrackedWorking: 115,
    systemMaxCrackedNotWorking: 70,
  },
  {
    id: "apple-ipad-air-5",
    category: "tablet",
    brand: "Apple",
    model: "iPad Air 5",
    systemMaxBrandNew: 365,
    systemMaxExcellent: 325,
    systemMaxGood: 290,
    systemMaxFair: 245,
    systemMaxCrackedWorking: 155,
    systemMaxCrackedNotWorking: 80,
  },
  {
    id: "apple-ipad-10",
    category: "tablet",
    brand: "Apple",
    model: "iPad 10th Gen",
    systemMaxBrandNew: 285,
    systemMaxExcellent: 250,
    systemMaxGood: 220,
    systemMaxFair: 185,
    systemMaxCrackedWorking: 120,
    systemMaxCrackedNotWorking: 70,
  },
  {
    id: "samsung-tab-s9",
    category: "tablet",
    brand: "Samsung",
    model: "Galaxy Tab S9",
    systemMaxBrandNew: 380,
    systemMaxExcellent: 335,
    systemMaxGood: 300,
    systemMaxFair: 255,
    systemMaxCrackedWorking: 165,
    systemMaxCrackedNotWorking: 95,
  },
  {
    id: "apple-macbook-air-m2",
    category: "laptop",
    brand: "Apple",
    model: "MacBook Air M2",
    systemMaxBrandNew: 780,
    systemMaxExcellent: 720,
    systemMaxGood: 660,
    systemMaxFair: 570,
    systemMaxCrackedWorking: 390,
    systemMaxCrackedNotWorking: 200,
  },
  {
    id: "apple-macbook-pro-14",
    category: "laptop",
    brand: "Apple",
    model: "MacBook Pro 14",
    systemMaxBrandNew: 1180,
    systemMaxExcellent: 1080,
    systemMaxGood: 980,
    systemMaxFair: 830,
    systemMaxCrackedWorking: 550,
    systemMaxCrackedNotWorking: 280,
  },
  {
    id: "dell-xps-13",
    category: "laptop",
    brand: "Dell",
    model: "XPS 13",
    systemMaxBrandNew: 620,
    systemMaxExcellent: 560,
    systemMaxGood: 500,
    systemMaxFair: 425,
    systemMaxCrackedWorking: 275,
    systemMaxCrackedNotWorking: 145,
  },
  {
    id: "sony-ps5",
    category: "gaming_device",
    brand: "Sony",
    model: "PlayStation 5",
    systemMaxBrandNew: 330,
    systemMaxExcellent: 290,
    systemMaxGood: 255,
    systemMaxFair: 215,
    systemMaxCrackedWorking: 150,
    systemMaxCrackedNotWorking: 80,
  },
  {
    id: "microsoft-xbox-series-x",
    category: "gaming_device",
    brand: "Microsoft",
    model: "Xbox Series X",
    systemMaxBrandNew: 310,
    systemMaxExcellent: 275,
    systemMaxGood: 240,
    systemMaxFair: 205,
    systemMaxCrackedWorking: 135,
    systemMaxCrackedNotWorking: 75,
  },
  {
    id: "nintendo-switch-oled",
    category: "gaming_device",
    brand: "Nintendo",
    model: "Switch OLED",
    systemMaxBrandNew: 220,
    systemMaxExcellent: 195,
    systemMaxGood: 170,
    systemMaxFair: 145,
    systemMaxCrackedWorking: 90,
    systemMaxCrackedNotWorking: 45,
  },
];
