import type { DeviceCategory } from "@/lib/trade/shared";

export type SeedDeviceModel = {
  id: string;
  category: DeviceCategory;
  brand: string;
  model: string;
  imageUrl?: string;
  systemMaxBrandNew: number;
  systemMaxExcellent: number;
  systemMaxGood: number;
  systemMaxFair: number;
  systemMaxCrackedWorking: number;
  systemMaxCrackedNotWorking: number;
};

export const seedDeviceModels: SeedDeviceModel[] = [
  // --- iPhone pricing below marked "placeholder" is interpolated from neighbouring
  // models, not confirmed — replace with real figures when supplied.
  {
    id: "apple-iphone-17-pro-max",
    category: "phone",
    brand: "Apple",
    model: "iPhone 17 Pro Max",
    imageUrl: "/brand/models/iphone-17-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 830,
    systemMaxExcellent: 760,
    systemMaxGood: 695,
    systemMaxFair: 610,
    systemMaxCrackedWorking: 400,
    systemMaxCrackedNotWorking: 220,
  },
  {
    id: "apple-iphone-17-pro",
    category: "phone",
    brand: "Apple",
    model: "iPhone 17 Pro",
    imageUrl: "/brand/models/iphone-17-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 760,
    systemMaxExcellent: 700,
    systemMaxGood: 640,
    systemMaxFair: 560,
    systemMaxCrackedWorking: 365,
    systemMaxCrackedNotWorking: 200,
  },
  {
    id: "apple-iphone-17",
    category: "phone",
    brand: "Apple",
    model: "iPhone 17",
    imageUrl: "/brand/models/iphone-17.webp",
    // placeholder pricing
    systemMaxBrandNew: 560,
    systemMaxExcellent: 510,
    systemMaxGood: 465,
    systemMaxFair: 405,
    systemMaxCrackedWorking: 270,
    systemMaxCrackedNotWorking: 150,
  },
  {
    id: "apple-iphone-air",
    category: "phone",
    brand: "Apple",
    model: "iPhone Air",
    imageUrl: "/brand/models/iphone-air.webp",
    // placeholder pricing
    systemMaxBrandNew: 620,
    systemMaxExcellent: 565,
    systemMaxGood: 515,
    systemMaxFair: 450,
    systemMaxCrackedWorking: 295,
    systemMaxCrackedNotWorking: 165,
  },
  {
    id: "apple-iphone-16-pro-max",
    category: "phone",
    brand: "Apple",
    model: "iPhone 16 Pro Max",
    imageUrl: "/brand/models/iphone-16-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 770,
    systemMaxExcellent: 705,
    systemMaxGood: 645,
    systemMaxFair: 565,
    systemMaxCrackedWorking: 365,
    systemMaxCrackedNotWorking: 205,
  },
  {
    id: "apple-iphone-16-pro",
    category: "phone",
    brand: "Apple",
    model: "iPhone 16 Pro",
    imageUrl: "/brand/models/iphone-16-pro-promax.webp",
    systemMaxBrandNew: 720,
    systemMaxExcellent: 660,
    systemMaxGood: 605,
    systemMaxFair: 530,
    systemMaxCrackedWorking: 340,
    systemMaxCrackedNotWorking: 190,
  },
  {
    id: "apple-iphone-16-plus",
    category: "phone",
    brand: "Apple",
    model: "iPhone 16 Plus",
    imageUrl: "/brand/models/iphone-16-16plus.webp",
    // placeholder pricing
    systemMaxBrandNew: 540,
    systemMaxExcellent: 490,
    systemMaxGood: 450,
    systemMaxFair: 395,
    systemMaxCrackedWorking: 265,
    systemMaxCrackedNotWorking: 150,
  },
  {
    id: "apple-iphone-16",
    category: "phone",
    brand: "Apple",
    model: "iPhone 16",
    imageUrl: "/brand/models/iphone-16-16plus.webp",
    // placeholder pricing
    systemMaxBrandNew: 500,
    systemMaxExcellent: 455,
    systemMaxGood: 415,
    systemMaxFair: 365,
    systemMaxCrackedWorking: 245,
    systemMaxCrackedNotWorking: 140,
  },
  {
    id: "apple-iphone-16e",
    category: "phone",
    brand: "Apple",
    model: "iPhone 16e",
    imageUrl: "/brand/models/iphone-16e.webp",
    // placeholder pricing
    systemMaxBrandNew: 380,
    systemMaxExcellent: 340,
    systemMaxGood: 310,
    systemMaxFair: 270,
    systemMaxCrackedWorking: 180,
    systemMaxCrackedNotWorking: 100,
  },
  {
    id: "apple-iphone-15-pro-max",
    category: "phone",
    brand: "Apple",
    model: "iPhone 15 Pro Max",
    imageUrl: "/brand/models/iphone-15-pro-promax.webp",
    systemMaxBrandNew: 690,
    systemMaxExcellent: 630,
    systemMaxGood: 575,
    systemMaxFair: 500,
    systemMaxCrackedWorking: 325,
    systemMaxCrackedNotWorking: 180,
  },
  {
    id: "apple-iphone-15-pro",
    category: "phone",
    brand: "Apple",
    model: "iPhone 15 Pro",
    imageUrl: "/brand/models/iphone-15-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 610,
    systemMaxExcellent: 560,
    systemMaxGood: 510,
    systemMaxFair: 445,
    systemMaxCrackedWorking: 290,
    systemMaxCrackedNotWorking: 160,
  },
  {
    id: "apple-iphone-15",
    category: "phone",
    brand: "Apple",
    model: "iPhone 15",
    imageUrl: "/brand/models/iphone-15-15plus.webp",
    systemMaxBrandNew: 520,
    systemMaxExcellent: 470,
    systemMaxGood: 430,
    systemMaxFair: 380,
    systemMaxCrackedWorking: 260,
    systemMaxCrackedNotWorking: 150,
  },
  {
    id: "apple-iphone-14-pro-max",
    category: "phone",
    brand: "Apple",
    model: "iPhone 14 Pro Max",
    imageUrl: "/brand/models/iphone-14-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 560,
    systemMaxExcellent: 510,
    systemMaxGood: 465,
    systemMaxFair: 410,
    systemMaxCrackedWorking: 270,
    systemMaxCrackedNotWorking: 150,
  },
  {
    id: "apple-iphone-14-pro",
    category: "phone",
    brand: "Apple",
    model: "iPhone 14 Pro",
    imageUrl: "/brand/models/iphone-14-pro-promax.webp",
    // placeholder pricing
    systemMaxBrandNew: 520,
    systemMaxExcellent: 475,
    systemMaxGood: 435,
    systemMaxFair: 380,
    systemMaxCrackedWorking: 250,
    systemMaxCrackedNotWorking: 140,
  },
  {
    id: "apple-iphone-14",
    category: "phone",
    brand: "Apple",
    model: "iPhone 14",
    imageUrl: "/brand/models/iphone-13-14.webp",
    systemMaxBrandNew: 430,
    systemMaxExcellent: 390,
    systemMaxGood: 355,
    systemMaxFair: 315,
    systemMaxCrackedWorking: 220,
    systemMaxCrackedNotWorking: 130,
  },
  {
    id: "apple-iphone-13",
    category: "phone",
    brand: "Apple",
    model: "iPhone 13",
    imageUrl: "/brand/models/iphone-13-14.webp",
    systemMaxBrandNew: 355,
    systemMaxExcellent: 315,
    systemMaxGood: 280,
    systemMaxFair: 240,
    systemMaxCrackedWorking: 165,
    systemMaxCrackedNotWorking: 100,
  },
  {
    id: "samsung-galaxy-s24",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy S24",
    systemMaxBrandNew: 470,
    systemMaxExcellent: 420,
    systemMaxGood: 385,
    systemMaxFair: 330,
    systemMaxCrackedWorking: 225,
    systemMaxCrackedNotWorking: 135,
  },
  {
    id: "samsung-galaxy-s24-ultra",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy S24 Ultra",
    systemMaxBrandNew: 640,
    systemMaxExcellent: 585,
    systemMaxGood: 535,
    systemMaxFair: 470,
    systemMaxCrackedWorking: 305,
    systemMaxCrackedNotWorking: 175,
  },
  {
    id: "samsung-galaxy-s23",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy S23",
    systemMaxBrandNew: 360,
    systemMaxExcellent: 320,
    systemMaxGood: 290,
    systemMaxFair: 250,
    systemMaxCrackedWorking: 175,
    systemMaxCrackedNotWorking: 105,
  },
  {
    id: "samsung-galaxy-z-flip-6",
    category: "phone",
    brand: "Samsung",
    model: "Galaxy Z Flip 6",
    systemMaxBrandNew: 520,
    systemMaxExcellent: 465,
    systemMaxGood: 420,
    systemMaxFair: 360,
    systemMaxCrackedWorking: 225,
    systemMaxCrackedNotWorking: 135,
  },
  {
    id: "google-pixel-8",
    category: "phone",
    brand: "Google",
    model: "Pixel 8",
    systemMaxBrandNew: 340,
    systemMaxExcellent: 300,
    systemMaxGood: 270,
    systemMaxFair: 230,
    systemMaxCrackedWorking: 155,
    systemMaxCrackedNotWorking: 95,
  },
  {
    id: "google-pixel-7",
    category: "phone",
    brand: "Google",
    model: "Pixel 7",
    systemMaxBrandNew: 250,
    systemMaxExcellent: 220,
    systemMaxGood: 195,
    systemMaxFair: 165,
    systemMaxCrackedWorking: 115,
    systemMaxCrackedNotWorking: 70,
  },
  {
    id: "apple-ipad-air-5",
    category: "tablet",
    brand: "Apple",
    model: "iPad Air 5",
    systemMaxBrandNew: 365,
    systemMaxExcellent: 325,
    systemMaxGood: 290,
    systemMaxFair: 245,
    systemMaxCrackedWorking: 155,
    systemMaxCrackedNotWorking: 80,
  },
  {
    id: "apple-ipad-10",
    category: "tablet",
    brand: "Apple",
    model: "iPad 10th Gen",
    systemMaxBrandNew: 285,
    systemMaxExcellent: 250,
    systemMaxGood: 220,
    systemMaxFair: 185,
    systemMaxCrackedWorking: 120,
    systemMaxCrackedNotWorking: 70,
  },
  {
    id: "samsung-tab-s9",
    category: "tablet",
    brand: "Samsung",
    model: "Galaxy Tab S9",
    systemMaxBrandNew: 380,
    systemMaxExcellent: 335,
    systemMaxGood: 300,
    systemMaxFair: 255,
    systemMaxCrackedWorking: 165,
    systemMaxCrackedNotWorking: 95,
  },
  {
    id: "apple-macbook-air-m2",
    category: "laptop",
    brand: "Apple",
    model: "MacBook Air M2",
    systemMaxBrandNew: 780,
    systemMaxExcellent: 720,
    systemMaxGood: 660,
    systemMaxFair: 570,
    systemMaxCrackedWorking: 390,
    systemMaxCrackedNotWorking: 200,
  },
  {
    id: "apple-macbook-pro-14",
    category: "laptop",
    brand: "Apple",
    model: "MacBook Pro 14",
    systemMaxBrandNew: 1180,
    systemMaxExcellent: 1080,
    systemMaxGood: 980,
    systemMaxFair: 830,
    systemMaxCrackedWorking: 550,
    systemMaxCrackedNotWorking: 280,
  },
  {
    id: "dell-xps-13",
    category: "laptop",
    brand: "Dell",
    model: "XPS 13",
    systemMaxBrandNew: 620,
    systemMaxExcellent: 560,
    systemMaxGood: 500,
    systemMaxFair: 425,
    systemMaxCrackedWorking: 275,
    systemMaxCrackedNotWorking: 145,
  },
  {
    id: "sony-ps5",
    category: "gaming_device",
    brand: "Sony",
    model: "PlayStation 5",
    systemMaxBrandNew: 330,
    systemMaxExcellent: 290,
    systemMaxGood: 255,
    systemMaxFair: 215,
    systemMaxCrackedWorking: 150,
    systemMaxCrackedNotWorking: 80,
  },
  {
    id: "microsoft-xbox-series-x",
    category: "gaming_device",
    brand: "Microsoft",
    model: "Xbox Series X",
    systemMaxBrandNew: 310,
    systemMaxExcellent: 275,
    systemMaxGood: 240,
    systemMaxFair: 205,
    systemMaxCrackedWorking: 135,
    systemMaxCrackedNotWorking: 75,
  },
  {
    id: "nintendo-switch-oled",
    category: "gaming_device",
    brand: "Nintendo",
    model: "Switch OLED",
    systemMaxBrandNew: 220,
    systemMaxExcellent: 195,
    systemMaxGood: 170,
    systemMaxFair: 145,
    systemMaxCrackedWorking: 90,
    systemMaxCrackedNotWorking: 45,
  },
];
